name: Docker

on:
  schedule:
    - cron: '16 1 * * *'
  push:
    branches: [ "development" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "development" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # This will include the org/repo in uppercase.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set IMAGE_NAME to lowercase
        id: lowercase_image_name
        run: |
          echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}  # Use the lowercase IMAGE_NAME
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}  # Use lowercase tag
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}



  modifygit:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: changing the deployment of git repo
      with:
        repository: 'MuhammadJamee/argoinfra'
        token: ${{ secrets.GIT_PASSWORD }}
        
    - name: modify the image
      run: |
        git config user.email jameeghouri@gmail.com  
        git config user.name muhammadjamee
        sed -Ei "s/(tag:).*/\1 ${GITHUB_RUN_NUMBER}/" tomcat/values-$(basename ${{ github.ref }}).yaml  # Replace with GitHub run number
        git add .
        git commit -m "Done by Github Actions Job changemanifest: ${{ github.run_number }}"
        git push origin main
        
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        token: ${{ secrets.GIT_PASSWORD }}
        GITHUB_RUN_NUMBER: ${{ github.run_number }}  # Pass GitHub run number as environment variable
